### ISSUE TITLE
Getting some sort of error 

### ISSUE THREAD

**Issue by vpierre1776** [sureshfizzy/CineSync#25] opened 2024-09-23 20:40 UTC
I am getting some sort of error . No clue what it means, will it cause issues ?

v"2024-09-23 20:27:45 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:45 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:45 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:45 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:45 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:45 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:45 [INFO] Found movie: X Men Apocalypse (2016)
2024-09-23 20:27:45 [INFO] Found movie: X Men Apocalypse (2016)
2024-09-23 20:27:45 [INFO] Found movie: X (2022)
2024-09-23 20:27:46 [INFO] Processed file: /mnt/remote/realdebrid/torrents/Wrong.Turn.2021.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT/Wrong.Turn.2021.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT.mkv to /mnt/storage/media/CineSync/Movies/1080pRemux/Wrong Turn (2021)/Wrong Turn (2021).mkv
2024-09-23 20:27:46 [INFO] Found movie: X (2022)
2024-09-23 20:27:46 [INFO] Processed file: /mnt/remote/realdebrid/torrents/X-Men.Apocalypse.2016.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-TERMiNAL/00077.m2ts to /mnt/storage/media/CineSync/Movies/Movies/X Men Apocalypse (2016)/X Men Apocalypse (2016).m2ts
2024-09-23 20:27:46 [INFO] Removed existing symlink for X Men Apocalypse (2016).m2ts
2024-09-23 20:27:46 [INFO] Processed file: /mnt/remote/realdebrid/torrents/X.2022.1080p.AMZN.WEB-DL.HINDI.ENGLISH.TELUGU.TAMIL.DDP5.1.H.265-GOPIHD.mkv/X.2022.1080p.AMZN.WEB-DL.HINDI.ENGLISH.TELUGU.TAMIL.DDP5.1.H.265-GOPIHD.mkv to /mnt/storage/media/CineSync/Movies/FullHD/X (2022)/X (2022).mkv
2024-09-23 20:27:46 [INFO] Processed file: /mnt/remote/realdebrid/torrents/X-Men.Apocalypse.2016.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-TERMiNAL/00006.m2ts to /mnt/storage/media/CineSync/Movies/Movies/X Men Apocalypse (2016)/X Men Apocalypse (2016).m2ts
2024-09-23 20:27:46 [INFO] Found movie: XX (2017)
2024-09-23 20:27:46 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:46 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value
2024-09-23 20:27:46 [ERROR] Task failed with exception: cannot access local variable 'proper_show_name' where it is not associated with a value
Traceback (most recent call last):
  File "/app/MediaHub/processors/symlink_creator.py", line 125, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/MediaHub/processors/show_processor.py", line 179, in process_show
    tmdb_id_match = re.search(r'\{tmdb-(\d+)\}$', proper_show_name)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'proper_show_name' where it is not associated with a value"

**Comment by sureshfizzy** [comment] 2024-09-24 01:46
Something to do with previous commit, I'll check what messed up. You have enabled tmdb folder I'd right on your env file ?

**Comment by sureshfizzy** [comment] 2024-09-24 03:34
@vpierre1776 is that the latest codebase ? i'm not able to hit with that error.

**Comment by vpierre1776** [comment] 2024-09-24 19:20
> Something to do with previous commit, I'll check what messed up. You have enabled tmdb folder I'd right on your env file ?

Yes I have enabled the "TMDb" feature should I disable ?

**Comment by sureshfizzy** [comment] 2024-09-24 20:23
> > Something to do with previous commit, I'll check what messed up. You have enabled tmdb folder I'd right on your env file ?
> 
> Yes I have enabled the "TMDb" feature should I disable ?

I enabled and tried the same, i didn't face any errors. Have you pulled the new docker image ?

**Comment by sureshfizzy** [comment] 2024-10-08 06:55
@vpierre1776 is it still happening ? also which format is .m2ts

**Comment by vpierre1776** [comment] 2024-10-08 20:50
> @vpierre1776 is it still happening ? also which format is .m2ts

Hi. No it's still showing errors "https://pastebin.com/FWueqbWs" , however it still creates  a large number of movies. fbut a hand full of shows only.  I have done several clean installs to see if it was a OS issue with Ubuntu.

**Comment by sureshfizzy** [comment] 2024-10-09 01:14
Which api key did you pick ? The larger or the shorter one ?

**Comment by vpierre1776** [comment] 2024-10-09 04:18
> Which api key did you pick ? The larger or the shorter one ?

In that pastebein link from earlier was the long / read access token.  But  I have gone back and forth between the two API keys.  this is from the shorter Api key one. " https://pastebin.com/5LLsptUC".

**Comment by sureshfizzy** [comment] 2024-10-09 04:45
Shorter one should work and it's working here, can you pass single folder alone and share me full output from start including the code passed ?

Get inside the project directory and Run with this

python3 Mediahub/main.py "path/to/folder" --auto-select

For eg:
python3 Mediahub/main.py "/mnt/zurg/shows/Breaking.bad.s01.mkv" --auto-select

**Comment by sureshfizzy** [comment] 2024-10-09 06:51
Pull new code and try it out, it will fix your issue

**Comment by vpierre1776** [comment] 2024-10-09 19:05
It works! Thanks a lot. Out of curiously what was the issue ? "https://pastebin.com/LxJF9jjd".

**Comment by vpierre1776** [comment] 2024-10-09 19:05
> Pull new code and try it out, it will fix your issue

It works! Thanks a lot. Out of curiously what was the issue ? "https://pastebin.com/LxJF9jjd".

**Comment by sureshfizzy** [comment] 2024-10-09 19:54
Glad it worked :), I've adjusted the api usage and the method calling.

https://github.com/sureshfizzy/CineSync/commit/dd8c7c08a128fb291d0ac30a07a1e1101e67010a#diff-65dc379561450956ec9443fbed8d24e55a07068fdaeea4971a628e0872946389R108

**Comment by vpierre1776** [comment] 2024-10-09 23:52
> Glad it worked :), I've adjusted the api usage and the method calling.
> 
> [dd8c7c0#diff-65dc379561450956ec9443fbed8d24e55a07068fdaeea4971a628e0872946389R108](https://github.com/sureshfizzy/CineSync/commit/dd8c7c08a128fb291d0ac30a07a1e1101e67010a#diff-65dc379561450956ec9443fbed8d24e55a07068fdaeea4971a628e0872946389R108)

Thought I was messing it up some how with my settings. Thanks

**Comment by sureshfizzy** [comment] 2024-10-10 05:35
> > Glad it worked :), I've adjusted the api usage and the method calling.
> > [dd8c7c0#diff-65dc379561450956ec9443fbed8d24e55a07068fdaeea4971a628e0872946389R108](https://github.com/sureshfizzy/CineSync/commit/dd8c7c08a128fb291d0ac30a07a1e1101e67010a#diff-65dc379561450956ec9443fbed8d24e55a07068fdaeea4971a628e0872946389R108)
> 
> Thought I was messing it up some how with my settings. Thanks

No, it isn't, the problem is that I couldn't recreate it before because it happened so rare. I'm closing this issue now that it has been resolved. Feel free to open new issues :)

**Closed by sureshfizzy** 2024-10-10 05:35 UTC
