### ISSUE TITLE
Add ability to disable symlink deletion in docker

### ISSUE THREAD

**Issue by idanlah** [sureshfizzy/CineSync#31] opened 2024-11-15 16:54 UTC
In docker version, is it possible to add an .env param to control whether to enable or disable symlink removal?
the issue is that sometimes the rclone container is unavailable or hasn't started yet so cinesync thinks the files were removed and keeps deleting everything. 

if you think another solution for this issue is more appropriate or better please share

**Comment by sureshfizzy** [comment] 2024-11-15 17:10
Instead of disabling removals, how about adding some variables like RCLONE_MOUNT= true

If enabled, it will check for the mounted directories and if it is unmounted, it will wait for it to come online untill further actions are taken. It's just an idea, feel free to add yours I'll check on them.

**Comment by idanlah** [comment] 2024-11-15 17:27
@sureshfizzy sure, your idea is better but I don't think the script is aware of which implementation is used for the directories, its not aware of any rclone.
So how can the script check if a directory is actually mounted or not just empty with no movies or shows?
I once thought of just checking if there is a version.txt in the root folder but it's very specific to zurg and zurg can change the structure anytime.

lmk what you think

**Comment by sureshfizzy** [comment] 2024-11-15 17:57
Rclone is currently far away from the script as this script is standalone. I need to make another specific script to check for the rclone directory mount or improve the polling monitor to specially verify if it is enabled.

Also to confirm if it is the actually mounted directory or not, as you said we can pass a simple version.txt inside that mount folder.

**Comment by sureshfizzy** [comment] 2024-11-17 07:35
@idanlah New improvements for rclone-specific functions have been pushed, you can test them. By default, the variables are false, and only set to true if it is a rclone-mounted directory.

**Comment by idanlah** [comment] 2024-11-17 08:46
thank you very much!, but i don't think this code will work if rclone is an external docker container because there is not rclone process inside the CineSync container.
i don't think CineSync container is aware of any rclone as i said in my previous comment. 
for example, in my setup i have rclone_zurg container and cinesync container and i just bind my rclone path using volume bind meaning that rclone_zurg binds /zurg to my host and cinecsync binds /zurg from host to cineSync container.

`    if os.getenv('RCLONE_MOUNT', 'false').lower() == 'true':
        try:
            result = subprocess.run(
                ['ps', 'aux'],
                capture_output=True,
                text=True
            )
            if result.returncode == 0:
                # Look for a specific rclone mount process related to this path
                rclone_found = False
                for line in result.stdout.split('\n'):
                    if 'rclone' in line and 'mount' in line and path in line:
                        rclone_found = True
                        if mount_state is not True:
                            log_message(f"Found rclone mount point at: {path}", level="INFO")
                        return True, path

                if not rclone_found:
                    log_message(f"Path {path} is a mount point but no rclone process found for it", level="DEBUG")
                    return False, None`

**Comment by sureshfizzy** [comment] 2024-11-17 08:56
I made this in a different workaround, basically when you enable it to true, it just counts the entire source directory as a rclone mount even if it is a local directory. This has been done intentionally to avoid docker issues as you said.

**Comment by idanlah** [comment] 2024-11-17 11:38
@sureshfizzy thanks ill check, can you also point me to where this workaround is the code?

**Comment by sureshfizzy** [comment] 2024-11-17 13:40
> @sureshfizzy thanks ill check, can you also point me to where this workaround is the code?

https://github.com/sureshfizzy/CineSync/blob/main/MediaHub/monitor/polling_monitor.py#L77

Since this condition is too broad when we set RCLONE_MOUNT to true it is ideally considering local directories as rclone even if the directory is not related to rclone. It is better to turn off the Condition when not needed.

**Comment by idanlah** [comment] 2024-11-17 13:53
@sureshfizzy i still don't understand:
`if 'rclone' in line and 'mount' in line and path in line`

in my case in docker, it will never find any rclone process in `result = subprocess.run` (because my rclone is running as a different container)  so it will never find "rclone" and "mount" in the result and it will never enter this 'if' statement.
so it will never return True and will wait indefinitely for the mount.

what am i missing?

**Comment by sureshfizzy** [comment] 2024-11-17 14:06
> @sureshfizzy i still don't understand: `if 'rclone' in line and 'mount' in line and path in line`
> 
> in my case in docker, it will never find any rclone process in `result = subprocess.run` (because my rclone is running as a different container) so it will never find "rclone" and "mount" in the result and it will never enter this 'if' statement. so it will never return True and will wait indefinitely for the mount.
> 
> what am i missing?

The point is it never finds rclone process :) it is just a variable check based on RCLONE_MOUNT, others are just for failsafe if things get worse

for eg: let's take a directory

/home/user/mount -- if rclone_mount is set to true it treats as mount directory, if it is false it will be treated as non mount directory

**Comment by idanlah** [comment] 2024-11-17 16:54
sure, i got:

```
2024-11-17 16:53:31 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'

2024-11-17 16:53:31 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies

2024-11-17 16:53:31 [INFO] Waiting for mount directory to become available...

2024-11-17 16:53:41 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'

2024-11-17 16:53:51 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
```

**Comment by sureshfizzy** [comment] 2024-11-17 17:05
> sure, i got:
> 
> ```
> 2024-11-17 16:53:31 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
> 
> 2024-11-17 16:53:31 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies
> 
> 2024-11-17 16:53:31 [INFO] Waiting for mount directory to become available...
> 
> 2024-11-17 16:53:41 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
> 
> 2024-11-17 16:53:51 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
> ```

Ok, i guess alpine docker doesn't recognise ps command, can you run which ps to check if it is able to find one ?

If not try installing it.

apt install procps

**Comment by idanlah** [comment] 2024-11-17 17:12
@sureshfizzy installed procps and rclone. now getting:

```
2024-11-17 17:10:00 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies

2024-11-17 17:10:00 [INFO] Waiting for mount directory to become available...
```

as i thought, because it can't find any rclone mount INSIDE the cinesync container. rclone mount is not done inside cinesync container.
it will only work on regular host setup

**Comment by sureshfizzy** [comment] 2024-11-17 17:18
> @sureshfizzy installed procps and rclone. now getting:
> 
> ```
> 2024-11-17 17:10:00 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies
> 
> 2024-11-17 17:10:00 [INFO] Waiting for mount directory to become available...
> ```
> 
> as i thought, because it can't find any rclone mount INSIDE the cinesync container. rclone mount is not done inside cinesync container. it will only work on regular host setup

I'm sure I'm missing something coz when I tested it, it does work without issues on docker. I'll check this tomorrow morning and drop a fix soon. Also can you let me know your setup so that I can have the same setup on mine and test it

**Comment by idanlah** [comment] 2024-11-17 18:54
when you tested it did you install rclone inside the cinesync docker container?

here is my setup:
```
  rclone_zurg:
    image: rclone/rclone
    container_name: rclone_zurg
    restart: unless-stopped
    networks:
      - t2_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $USERDIR/zurg:/data:rshared 
      - $DOCKERDIR/rclone/config:/config/rclone
      - /etc/passwd:/etc/passwd:rodc 
      - /etc/group:/etc/group:ro
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm.
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://zurg:9999 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    command: "mount zurg: /data --vfs-cache-mode full --allow-other --allow-non-empty --uid=1000 --gid=1000 --umask=002 --dir-cache-time 10s"
```

```
  cinesync:
    image: sureshfizzy/cinesync:latest
    networks:
      - t2_proxy
    tty: true
    command: ["python3", "MediaHub/main.py", "--auto-select"]
    entrypoint: ["/custom_entrypoint.sh"]
    container_name: cinesync
    # restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $USERDIR/zurg/:/zurg  # Mount home directory to provide access to home files
      - $USERDIR/media:/mnt  # Mount /mnt for access to external storage
      - $DOCKERDIR/cinesync/db:/app/db  # Mount local db folder to persist database files
      - $DOCKERDIR/cinesync/.env:/app/.env
      - ./custom_entrypoint/cinesync/custom_entrypoint.sh:/custom_entrypoint.sh  # Adjust the path as necessary
    depends_on:
      rclone_zurg:
        condition: service_healthy
    healthcheck:
      test:  ["CMD", "sh", "-c", "test -f /zurg/version.txt || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
```

**Comment by sureshfizzy** [comment] 2024-11-18 07:39
@idanlah pick the latest Docker images and give it a try. According to the new commits, it should now work with Docker. If the mount gets disconnected, it will remain unavailable. At this point, you will need to restart the Docker container for the mount to be detected again, just like with other containers.

Also you don't need these command: ["python3", "MediaHub/main.py", "--auto-select"] as i mentioned previously

https://github.com/sureshfizzy/CineSync/blob/main/Dockerfile#L41

**Comment by idanlah** [comment] 2024-11-18 08:20
@sureshfizzy thanks you!, so it seems to be working but because zurg/ already has its own version.txt file in zurg/version.txt and this realdebrid is not writable i needed to add `MediaHub Rclone Mount Verification File` manually which caused issues.
what about just checking if there already exists version.txt with any content whatsoever?
if exists then the mount is available and can continue.
if not exists, then try and create version.txt.
wdyt?

**Comment by sureshfizzy** [comment] 2024-11-18 09:15
> @sureshfizzy thanks you!, so it seems to be working but because zurg/ already has its own version.txt file in zurg/version.txt and this realdebrid is not writable i needed to add `MediaHub Rclone Mount Verification File` manually which caused issues. what about just checking if there already exists version.txt with any content whatsoever? if exists then the mount is available and can continue. if not exists, then try and create version.txt. wdyt?

That makes a lot of sense in read-only directory. I've modified the code, you're fine to go now.

**Comment by sureshfizzy** [comment] 2024-11-18 17:08
> @sureshfizzy thanks, its working great now! just one small thing im trying to figure out: so when i exit the rclone_zurg container as expected cinesync stops recognizing the folder which is great:
> 
> `2024-11-18 16:39:02 [WARNING] Mount unavailable - Directory does not exist: /zurg/movies`
> 
> but when i restart rclone_zurg, cinesync doesn't re-poll and checks if the mount is available again for some reason, even though i see in the code that everything is inside a while true loop with ime.sleep(is_mount_check_interval()):
> 
> ```
>     while True:
>         try:
>             # Check if rclone mount is available (if enabled)
>             if not check_rclone_mount():
>                 if mount_state is not False:
>                     log_message("Mount not available, waiting for rclone mount...", level="INFO")
>                     mount_state = False
>                 #return False, False
>                 #time.sleep(mount_check_interval)
>                 time.sleep(is_mount_check_interval())
>                 continue
> 
>             # If this is our first successful mount check, do initial scan
>             if not current_files:
>                 current_files = initial_scan(src_dirs)
>                 log_message("Initial scan after mount verification completed, Monitor Service is Running", level="INFO")
> 
>             # Normal directory monitoring
>             log_message("Performing regular directory scan", level="DEBUG")
>             new_files = scan_directories(src_dirs, current_files)
>             process_changes(current_files, new_files, dest_dir)
>             current_files = new_files
> 
>             log_message(f"Sleeping for {sleep_time} seconds", level="DEBUG")
>             time.sleep(sleep_time)
> ```
> 
> do you know why? if a follow the code it should return False after `[WARNING] Mount unavailable - Directory does not exist: /zurg/movies` and then get back to continuing checking the mount again in the while loop

The issue is related to Docker's behavior. After zurg starts up, you'll need to restart the cinesync container to ensure it recognizes the mounted drive. This isn't a problem when running the service outside of Docker. The same behavior can be observed with other containers like radarr or sonarr, they often fail to recognize mounted drives until they are restarted.

With the current implementation, we can prevent the container to take further actions until it is able to recognise it again.

**Comment by idanlah** [comment] 2024-11-18 18:43
> > @sureshfizzy thanks, its working great now! just one small thing im trying to figure out: so when i exit the rclone_zurg container as expected cinesync stops recognizing the folder which is great:
> > `2024-11-18 16:39:02 [WARNING] Mount unavailable - Directory does not exist: /zurg/movies`
> > but when i restart rclone_zurg, cinesync doesn't re-poll and checks if the mount is available again for some reason, even though i see in the code that everything is inside a while true loop with ime.sleep(is_mount_check_interval()):
> > ```
> >     while True:
> >         try:
> >             # Check if rclone mount is available (if enabled)
> >             if not check_rclone_mount():
> >                 if mount_state is not False:
> >                     log_message("Mount not available, waiting for rclone mount...", level="INFO")
> >                     mount_state = False
> >                 #return False, False
> >                 #time.sleep(mount_check_interval)
> >                 time.sleep(is_mount_check_interval())
> >                 continue
> > 
> >             # If this is our first successful mount check, do initial scan
> >             if not current_files:
> >                 current_files = initial_scan(src_dirs)
> >                 log_message("Initial scan after mount verification completed, Monitor Service is Running", level="INFO")
> > 
> >             # Normal directory monitoring
> >             log_message("Performing regular directory scan", level="DEBUG")
> >             new_files = scan_directories(src_dirs, current_files)
> >             process_changes(current_files, new_files, dest_dir)
> >             current_files = new_files
> > 
> >             log_message(f"Sleeping for {sleep_time} seconds", level="DEBUG")
> >             time.sleep(sleep_time)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > do you know why? if a follow the code it should return False after `[WARNING] Mount unavailable - Directory does not exist: /zurg/movies` and then get back to continuing checking the mount again in the while loop
> 
> The issue is related to Docker's behavior. After zurg starts up, you'll need to restart the cinesync container to ensure it recognizes the mounted drive. This isn't a problem when running the service outside of Docker. The same behavior can be observed with other containers like radarr or sonarr, they often fail to recognize mounted drives until they are restarted.
> 
> With the current implementation, we can prevent the container to take further actions until it is able to recognise it again.

got it thank you!

**Comment by sureshfizzy** [comment] 2024-11-19 03:14
Marking as closed since it is completed.

**Closed by sureshfizzy** 2024-11-19 03:14 UTC
Labels: enhancement
